#!/usr/bin/env bash

# Enable aliases (required for flutter function)
shopt -s expand_aliases
. ~/.bash_aliases

# Increment version
version=`grep version: ./pubspec.yaml | cut -d ' ' -f 2`
version_num=`echo "$version" | cut -d '+' -f 2`
version_name=`echo "$version" | cut -d '+' -f 1`

if [ "$1" == "-n" ]; then
    if [ "$2" == "" ]; then
        build=`echo $version_name | cut -d '.' -f 3`
        ((build += 1))
        majmin=`echo "$version_name" | cut -d '.' -f 1-2`
        version_name="$majmin.$build"
    else
        version_name="$2"
    fi
fi

((version_num += 1))
sed -i -e '/version:/ s/:.*/: '"${version_name}+${version_num}"'/' ./pubspec.yaml

# Build app bundle
flutter build appbundle
